### PR TITLE
apply bug fixes from upstream

### PR DESCRIPTION
**Pull request by ksco**
This commit applies bug fixes from the following upstream commits:
1. https://github.com/Turbo87/utm/commit/eeed1f1cc54139c1b8ca6caf96193858fb1755e9
2. https://github.com/Turbo87/utm/commit/17e570cd3dde0b5daa774b68cbb7130ea2f0016c

### CODE REVIEW

**Comment by icholy** [comment]
Thanks, do you mind copying over the test cases from the linked commits?

**Comment by ksco** [comment]
Yes, I should definitely include the test as well.

**Comment by ksco** [comment]
Through testing, I found that Go's `math.Mod` and Python's `%` operator are not equivalent. Thanks for the advice!

**Comment by icholy** [comment]
Thanks, I've tagged this as `v1.0.1`

**Pull request merged**
